name: Check tags
on:
  pull_request
jobs:
  Test_Image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Checkout docker_tag registry
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository_owner }}/docker_tag
        ref: master
        token: ${{ secrets.token }}
        path: .github/actions/docker_tag
    - name: Build image without tag latest
      uses: ./.github/actions/docker_tag
      with:
        username: ${{ secrets.dockerhub_username }}
        password: ${{ secrets.docker_token }}
        repository: moleszek/salarycalculator
        tag_latest: false
        push: false
        github: false
        token: ${{ secrets.TOKEN }}
        owner: ${{ github.repository_owner }}
    - name: Build image with tag latest
      uses: ./.github/actions/docker_tag
      with:
        username: ${{ secrets.dockerhub_username }}
        password: ${{ secrets.docker_token }}
        repository: moleszek/salarycalculator
        tag_latest: true
        push: false
        github: false
        token: ${{ secrets.TOKEN }}
        owner: ${{ github.repository_owner }}