name: Test on Ubuntu
on:
  pull_request
jobs:
  Test_Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - run: dotnet test test/test.csproj