name: Push image to Docker Hub
on:
  release:
    types:
    - published
jobs:
  Publish_To_Docker_Hub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Checkout docker_tag registry
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository_owner }}/docker_tag
        ref: master
        token: ${{ secrets.token }}
        path: .github/actions/docker_tag
    - name: Publish to docker hub
      uses: ./.github/actions/docker_tag
      with:
        username: ${{ secrets.dockerhub_username }}
        password: ${{ secrets.docker_token }}
        repository: moleszek/salarycalculator
        tag_latest: false
        push: true
        github: false
        token: ${{ secrets.TOKEN }}
        owner: ${{ github.repository_owner }}
    - name: Update Docker README
      uses: peter-evans/dockerhub-description@v2.1.0
      env:
        DOCKERHUB_USERNAME: ${{ secrets.dockerhub_username }}
        DOCKERHUB_PASSWORD: ${{ secrets.dockerhub_password }}
        DOCKERHUB_REPOSITORY: moleszek/salarycalculator
        README_FILEPATH: README.md