name: Push image
on:
  release:
    types:
    - published
jobs:
  publish_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get docker_tag registry
      uses: actions/checkout@v2
      with:
        repository: solairen/docker_tag
        ref: master
        token: ${{ secrets.token }}
        path: .github/actions/solairen/docker_tag
    - name: Publish to docker hub
      uses: ./.github/actions/solairen/docker_tag
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: "moleszek/salarycalculator"
        tag_latest: "false"
        push: "true"
    - name: Update Docker README
      uses: peter-evans/dockerhub-description@v2.1.0
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        DOCKERHUB_REPOSITORY: moleszek/salarycalculator
        README_FILEPATH: README.md